### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by TheSangral** [Lyall/MGSHDFix#1]
Unlike the other MGS2 and 3 mod which also had this dll and a copy paste of files which worked, this one doesn't. With these files in the folder with the exe the game simply doesn't start.

**Comment by Lyall** [comment]
Can you upload your log file `MGSHDFix.log` please?

**Comment by Lukar115** [comment]
I was running into the same problem. I was able to get it to work by downloading [the latest version of the d3d11.dll for Ultimate ASI Loader](https://github.com/ThirteenAG/Ultimate-ASI-Loader/releases/download/x64-latest/) and replacing the one that's included in the mod with it.

**Comment by Lyall** [comment]
Thanks for posting that @Lukar115. I've updated the version of Ultimate ASI Loader that is included in the release build zips. Let me know if it works for you now @TheSangral.

**Comment by TheSangral** [comment]
> Thanks for posting that @Lukar115. I've updated the version of Ultimate ASI Loader that is included in the release build zips. Let me know if it works for you now @TheSangral.

Yes, now it works, thank you. But like @Lukar115 said, with this dll (don't know if the other one was supposed to do anything different tho), MGS2 has the exact same problems as with the mod from the other Person yesterday. Broken HUD and different screen layer effect which doesn't scale with the resolution and are stuck in the top left corner. Like cutscene black bars, different screen effects or the game over screen.

**Comment by Lyall** [comment]
> > Thanks for posting that @Lukar115. I've updated the version of Ultimate ASI Loader that is included in the release build zips. Let me know if it works for you now @TheSangral.
> 
> Yes, now it works, thank you. But like @Lukar115 said, with this dll (don't know if the other one was supposed to do anything different tho), MGS2 has the exact same problems as with the mod from the other Person yesterday. Broken HUD and different screen layer effect which doesn't scale with the resolution and are stuck in the top left corner. Like cutscene black bars, different screen effects or the game over screen.

What resolution are you playing the game at? I've added some scaling for some of the more egregious issues like the screen effects but they only apply at >16:9 aspect ratios.

**Comment by TheSangral** [comment]
> > > Thanks for posting that @Lukar115. I've updated the version of Ultimate ASI Loader that is included in the release build zips. Let me know if it works for you now @TheSangral.
> > 
> > 
> > Yes, now it works, thank you. But like @Lukar115 said, with this dll (don't know if the other one was supposed to do anything different tho), MGS2 has the exact same problems as with the mod from the other Person yesterday. Broken HUD and different screen layer effect which doesn't scale with the resolution and are stuck in the top left corner. Like cutscene black bars, different screen effects or the game over screen.
> 
> What resolution are you playing the game at? I've added some scaling for some of the more egregious issues like the screen effects but they only apply at >16:9 aspect ratios.
> 
> Edit: I have moved the hook for this over to it's own function so it will now run at any resolution, not just >16:9. Give v0.5 a try. There's probably more screen effects that will need to be scaled so it might be a case of whack-a-mole fixing these issues as they come up.

I was playing at 4K and 16:9, so weird that it didn't work and I now tested your new version and it still doesn't work unfortunately. Literally all over screen effects are still in the top left corner not scaled to 4K. It starts with the main menu when you select difficulty, you see a big rectangle in the top left and also mini subtitles. Goes over different effects while talking in Codec, goes over to cutscene bars and death glass shatter effect while dying in first person and the game over screen. I think I haven't seen one that's fixed with your version, oh, and of course the mini life bar.

I recorded a video of your new 0.5 version so you can compare.

https://www.youtube.com/watch?v=cjTx_Y5DzWU

I don't know why it's not working for me, I removed all the old files, even replaced the MGS2 exe with an untouched one, even used steamless with the exe and tried that, but none of the fixes are triggering for me.

**Comment by Lyall** [comment]
Your totally right. I was actually able to fix part of the problem before but it was incomplete and you pointing out that issue on the main menu has led me to something that might actually help. 

![METAL GEAR SOLID2_2023_10_27_04_30_55_708](https://github.com/Lyall/MGSHDFix/assets/695941/47d6ae92-25b5-4700-b8b4-b0230fe71a9a)
![METAL GEAR SOLID2_2023_10_27_04_31_49_445](https://github.com/Lyall/MGSHDFix/assets/695941/71ba31ec-0e97-43c3-ad9b-0b1a1c51c83a)
![METAL GEAR SOLID2_2023_10_27_04_32_12_869](https://github.com/Lyall/MGSHDFix/assets/695941/c4f59f2d-2331-4249-ad05-b1db84850782)

Bear with me while I fully test this, hopefully it's the path to fixing the issues caused in MGS2 by going beyond 720p.

**Comment by Lyall** [comment]
Alright this should be partially addressed in the latest build (v0.6). There's still some issues like the codec portrait scanlines. 

No Mod (1280x720)
![vanilla](https://github.com/Lyall/MGSHDFix/assets/695941/48512518-a33e-4a8d-be78-fcd7c819bb49)

Modded (2560x1440)
![METAL GEAR SOLID2_2023_10_28_01_39_08_785](https://github.com/Lyall/MGSHDFix/assets/695941/0c235498-3add-4c6e-8fa7-1db0d7187551)

**Comment by Lyall** [comment]
Okay I'm going to close this issue now and direct further issues with MGS 2 as a result of running a custom resolution over here #8

**Comment by ShizCalev** [comment]
Fixing broken issues, ignore this message.
