### ISSUE TITLE
[Bug] [MGS1]: BUG excessive zoom in the intro and in the water (game v1.5.0 correction)

### ISSUE THREAD

**Issue by j0hnnypearl** [Lyall/MGSHDFix#105]
## Issue Summary:

BUG excessive zoom in the intro and in the water.
I'm using the latest version 2.2 of the mod that fixes the game, but at the same time it's broken when using the "MGS1 only: Enables render resolve scaling" settings leaving the game with a huge Zoom in the intro and when you enter the water. Can anyone tell me if there will be a fix for this? Because this feature is the only one that leaves the game with playable graphics, because Konami did a terrible job in this port.

## MGSHDFix & Game Version Numbers: 

 Games - 1.5.1
MGSHDFix - 2.2

## Log Files:

[MGSM2Fix.log](https://github.com/user-attachments/files/17122570/MGSM2Fix.log)

## Reproduction:

my settings below in the mod are like this. "MGSM2Fix.ini"
;;;;;;;;;; General ;;;;;;;;;;

[External Resolution]
; Enter your chosen resolution.
; You can leave these at 0 if you want your desktop resolution used instead.
Enabled = true
Width = 0
Height = 0
Windowed = false
Borderless = true

[Internal Resolution]
; MGS1 only: Enables render resolution scaling.
; Width is controlled using the in-game settings. Leave the height at 0 to use the external resolution.
Enabled = true
Height = 0
Widescreen = true

![20240924203736_1](https://github.com/user-attachments/assets/4b1b82bf-0452-44a9-a251-c7ac61ebeb8e)
![20240924202903_1](https://github.com/user-attachments/assets/d74e4220-4a27-4c2e-ac54-7d246d3e2ac9)
![20240924203742_1](https://github.com/user-attachments/assets/5660ee48-022f-43b2-858f-d3aeaf8c0d11)

**Comment by Lyall** [comment]
I think you meant to post this issue over on the [MGSM2Fix repository](https://github.com/nuggslet/MGSM2Fix).

**Comment by j0hnnypearl** [comment]
No, I think you misunderstood me.

**Comment by j0hnnypearl** [comment]
but in that case, will there be some kind of correction in the future?

**Comment by Lyall** [comment]
> but in that case, will there be some kind of correction in the future?

It's not my project, so I can't say. I've done no work on the M2 ports that are included in Vol. 1. You would be better off asking there.
