### ISSUE TITLE
[Feature Request] MGS 2 | MGS 3: 30FPS support.

### ISSUE THREAD

**Issue by RIKLAVIEGASINTRODUCTION** [Lyall/MGSHDFix#11]
Would allow people with lower end machines to play the games without slow motion.

**Comment by yumtako** [comment]
Some dude on YouTube has been working on uncapping the framerate on mgs3 but as far as I know he's gone silent. (this is related since stopping the game from speeding up at high fps would also stop it from slowing down at lower fps)

**Comment by Lyall** [comment]
I would imagine this is theoretically possible given the Switch versions run at 30fps. Will need to look in to it further.

**Comment by ShizCalev** [comment]
https://github.com/cipherxof/MGSFPSUnlock

This mod provides the requested functionality btw (download for MGS2 is in pull requests.)

**Comment by robohappy** [comment]
I tried running MGSFPSUnlock https://github.com/cipherxof/MGSFPSUnlock alongside MGSHDFix, and it seems they conflict with each other and the game won't launch. Would it be possible to integrate MGSFPSUnlock's features into MGSHDFix?

**Comment by ShizCalev** [comment]
> I tried running MGSFPSUnlock https://github.com/cipherxof/MGSFPSUnlock alongside MGSHDFix, and it seems they conflict with each other and the game won't launch. Would it be possible to integrate MGSFPSUnlock's features into MGSHDFix?

https://github.com/cipherxof/MGSFPSUnlock/pull/27

use this version.
