### ISSUE TITLE
[Feature Request] [MGS3]: Option to disable the forced 4x MSAA 

### ISSUE THREAD

**Issue by tuca1234567890** [Lyall/MGSHDFix#116]
## Feature Summary:

I want to play the game without it being in slow-motion, but my main computer is dead and I only have a laptop right now. An option to disable the 4x MSAA would improve my framerate.

### Is your proposal related to a problem?

MGS3 runs at 30fps max in 800x600, which shouldn't happen with a PS2 game. PC Gaming Wiki says the game uses a forced 4x MSAA that can't be disabled, which I suspect is the cause. 

### Describe the solution you'd like

An option to completely disable anti-aliasing.

### Describe alternatives you've considered

None

**Comment by ShizCalev** [comment]
>which shouldn't happen with a PS2 game
MGS3 in the MC isn't a PS2 game, it's a HD Remaster made for the PS3 with chunks of the engine replaced with Bluepoint's Blast Factor remaster engine, which was then ported to DirectX 11 nearly a decade later.

________________

Assuming you're using a nvidia graphics chip, follow this guide - it fixes the issue 9 out of 10 times.

https://www.youtube.com/watch?v=rvaAfCBCJ2M

________________

if it doesn't would you mind sharing what your laptop's GPU is?

**Comment by tuca1234567890** [comment]
It's an 10th gen Intel UHD Graphics. I guess I probably should've expected it to not run well...

**Comment by ShizCalev** [comment]
Ah.

https://gpu.userbenchmark.com/Compare/Nvidia-GTX-970-vs-Intel-Iris-Plus-G7/2577vsm888370

Unfortunately your Integrated graphics chip is WAY below the minimum system requirements for MGS3.

> System Requirements
> 
>     Minimum:
>         Requires a 64-bit processor and operating system
>         OS: Windows 10(64-bit OS required)
>         Processor: Intel(R) Core(TM) i5-7500
>         Memory: 8 GB RAM
>         Graphics: NVIDIA GeForce GTX 970
>         DirectX: Version 11
>         Storage: 15 GB available space
>         Sound Card: DirectX 11 compatible sound card
>         Additional Notes: Xinput Controller required
>

**Comment by tuca1234567890** [comment]
Yeah, guess I'll just have to wait till my computer is fixed
