### ISSUE TITLE
Numerous issues on 5120x1440 monitors (MGS3)

### ISSUE THREAD

**Issue by MrTwisT007** [Lyall/MGSHDFix#19]
Edit: retracted (crossed out) some statements as they were not specific to the patch.

This is tested on MGS3 so far.

With a 32:9 monitor the patch seems to ignore the custom width setting.
With width set to 2560 the game still runs at 5120 and stretches everything to the entire screen width. Aspect ratio setting does not have effect on this.
~~Windowed causes the game to drop down to 2-3 FPS when the window is in focus and 60FPS when not in focus.~~
Borderless does not work as the game tries to display on the left side of the screen ~~, then proceeding to cause my monitor to lose signal and crash the game shortly after, restoring the signal (weird one).~~

Would really love to use this patch for the intro skip features, but have to fallback to MGSResolutionPatch for working pillarboxed solution. Can provide further info if needed.

**Comment by Lyall** [comment]
So I'm pretty sure the stretching issue when running for example 2560x1440 on a 3440x1440 display is due to the framebuffer fix. The fix stops pillarboxing if your maximum reported resolution is a different aspect ratio than 16:9.

**Comment by MrTwisT007** [comment]
Tried the test build - custom 2560x1440 borderless works in this one without stretching (pillarboxed).

**Comment by Lyall** [comment]
> Tried the test build - custom 2560x1440 borderless works in this one without stretching (pillarboxed).

Can you try out v0.8? It should accomplish the same thing but you'll have to set ```
[Framebuffer Fix]
; Forces the framebuffer size to be the same as the custom resolution.
; Disable this if you want pillarboxing/letterboxing with your custom resolution.
Enabled = true
```
to `false` in `MGSHDFix.ini`.

**Comment by MrTwisT007** [comment]
0.8 works as described. Thanks for getting this in!
