### ISSUE TITLE
MGS2/MGS3 beta branch

### ISSUE THREAD

**Issue by emoose** [Lyall/MGSHDFix#21]
Some public beta branches were added today for fixing the speed issues that some people get, might need to check if all hooks still work.

Branches are passworded but passwords are in the posts

MGS2: https://steamcommunity.com/games/2131640/announcements/detail/3750995043925349423
MGS3: https://steamcommunity.com/ogg/2131650/announcements/detail/3736358345139231632

MGS1 also has a beta too: https://steamcommunity.com/ogg/2131630/announcements/detail/3705959047643376958

E: MG1/2 also has a beta branch, wasn't highlighted on steam some reason: https://steamcommunity.com/games/2131680/announcements/detail/3704833147717876893

**Comment by Lyall** [comment]
I'm gonna make a bet that these are just enabling vsync at least based on the "workaround" they posted. Fingers crossed there is no large changes to the executables.

**Comment by emoose** [comment]
Looks like all games have been updated to the beta branch versions now: https://store.steampowered.com/news/app/2131650/view/3812920173340247249?l=english

**Comment by Lyall** [comment]
I've quickly fired up MG1/2, MGS2 and MGS3. Looks like all the sigs still work. Also seemed like it was all working correctly. Will need to check more in-depth later today.
