### ISSUE TITLE
MGS2 and MGS3 screen render or resolution problem 

### ISSUE THREAD

**Issue by bitn0zero** [Lyall/MGSHDFix#22]
going to different angels it makes a line going across the bottom left to the top right and it just looks like its tearing but its pretty hard to see them in mgs2 during the tanker mission I think it might be Aspect Ratio and v sync
![20231030074511_1](https://github.com/Lyall/MGSHDFix/assets/149389171/1e4cdf79-677d-4ecc-9fd0-1f78fadbf3c5)

**Comment by Lyall** [comment]
I have to admit I'm kind of struggling to see the problem here. Do you have any other screenshots that maybe show this issue more clearly?

**Comment by Lyall** [comment]
Is is similar to this issue?

https://youtu.be/1fZd4B9PHr4

**Comment by OddOttAllen** [comment]
issue is fixed now with the latest AMD driver update, so this probably doesn't need to be tweaked within MGSHDFix or anything

**Comment by Lyall** [comment]
As others have reported, it looks like this bug was fixed in the latest AMD Driver (Adrenalin Edition 24.1.1).
