### ISSUE TITLE
Intro Logo's not skipping

### ISSUE THREAD

**Issue by DarkSynn337** [Lyall/MGSHDFix#23]
Hi

Not sure if this is the right place to report it, very new to github, but got your recent release with the feature to skip intros.

Playing MGS3-NA and the logos aren't bring skipped, I do have the upscaled logos from Nexus Mods but that's just visual so I doubt they would be the cause etc.

When I come to test MGS2 and the different regions etc. I'll let you know if I get the same results.

Also, thanks for working on the fixes :)

**Comment by xenrohachi** [comment]
You need to go edit the .ini that comes with the mod and set skip intros to "true"

**Comment by DarkSynn337** [comment]
Oh god I'm an idiot.... I even saw the line of code in the earlier (source) builds knowing the feature was coming and I completely forgot to check there..... ugh.... thanks @xenrohachi very much appreciated :)
