### ISSUE TITLE
Game crashes after enable mouse sensitivity multiplier

### ISSUE THREAD

**Issue by fnaf135** [Lyall/MGSHDFix#24]
The other fixes worked fine in my game, but after i tried to enable the mouse sensitivity multiplier, the game would just pops up white screen and then it just crashes. Tested on NA version of the game
Edit: I just found out that I have to reopen the game about 3 times to get the game works with that fix enabled.

**Comment by Lyall** [comment]
Are you running v0.7? If so can you try out [this test build?](https://github.com/Lyall/MGSHDFix/files/13199496/MGSHDFix_v_0_7_mousetest.zip)

**Comment by RIKLAVIEGASINTRODUCTION** [comment]
Try disabling [Fix Aspect Ratio].

**Comment by fnaf135** [comment]
> Try disabling [Fix Aspect Ratio].

No such luck

**Comment by fnaf135** [comment]
> Are you running v0.7? If so can you try out [this test build?](https://github.com/Lyall/MGSHDFix/files/13199496/MGSHDFix_v_0_7_mousetest.zip)

This build works best for me

**Comment by Alexbeav** [comment]
> Are you running v0.7? If so can you try out [this test build?](https://github.com/Lyall/MGSHDFix/files/13199496/MGSHDFix_v_0_7_mousetest.zip)

This fixed it for me, as well as the alt-tab and clicking back into the game crash.

**Comment by fnaf135** [comment]
> > Are you running v0.7? If so can you try out [this test build?](https://github.com/Lyall/MGSHDFix/files/13199496/MGSHDFix_v_0_7_mousetest.zip)
> 
> This fixed it for me, as well as the alt-tab and clicking back into the game crash.
> 
> edit: this seems to disable mouse aiming however :(

My mouse aiming works fine to me

**Comment by Lyall** [comment]
This should be fixed in v0.8 based on feedback from the test build. @Alexbeav If you still have mouse aiming problems, feel free to open a new issue.
