### ISSUE TITLE
Disable Background Input

### ISSUE THREAD

**Issue by sgtlaggy** [Lyall/MGSHDFix#27]
I frequently Alt-Tab and type, but MGS3 acts a bit like a keylogger and reads all input, regardless of whether it has focus. As I type this, Snake is crouch spamming, shooting, spinning in circles, equipping and unequipping items, everything but standing still. Somehow I even managed to tranq something.

This feature may not entirely be within scope of the mod, but I figure it's worth a shot with the mouse settings implemented.

If possible, I'd like to keep background input only for controllers, but that may be asking a bit much.

**Comment by emoose** [comment]
Seems there's a `NHT_GetIsMinimized` function at 0x14004EA50 that the game checks with before it processes inputs, patching that to return 1 stops any keyboard inputs from working, looks like that func is checking some variable which is meant to be set by WndProc at 0x14004DA59, but I guess that wndproc might not be looking at the right message or something, hm
