### ISSUE TITLE
Steam Deck Issues

### ISSUE THREAD

**Issue by langiam** [Lyall/MGSHDFix#28]
I've encountered issues setting up the fix for MGS1 on steam deck. Following the instructions to just extract the file into the .exe folder and tweaking basic configuration settings the game remains unchanged. Is this a known issue?

**Comment by samuskay** [comment]
This fix is only for metal gear 1 and 2, and metal gear solid 2 and 3.

Metal gear solid 1 doesn't have a widescreen fix yet.

**Comment by xenrohachi** [comment]
Also worth noting, you will need to set a DLL override for the d3d11.dll for the game to recognize the mod in the supported titles. But as samuskay mentioned, MGS1 is not supported

**Comment by Lyall** [comment]
There's no support for MGS1 yet and probably won't be for quite some time.
