### ISSUE TITLE
[Request/Adding feature] Texture filtering on MGS2 & 3 at lowest quality, reducing texture filtering and texture quality.

### ISSUE THREAD

**Issue by Noname00000001** [Lyall/MGSHDFix#33]
Hello

I'm new to this and I honestly have no idea how much is possible to edit the games via this fix.
But since what have been made so far feels like magic, and is making the collection more and more refined and playable with each release, I'm wondering if it's possible to force the texture filtering to it's highest value, x16 I guess?

I know it can be forced in the graphics' cards settings, but it would be nice if it could be added to the fix for ease of access if possible.

Cheers and keep up the awesome work!

**Comment by KoKlusz** [comment]
https://github.com/Lyall/MGSHDFix/pull/31

**Comment by Noname00000001** [comment]
> #31

Cheers for adding it/showing me there already were talk about it ^_^
I guess this one can be closed?

**Comment by Lyall** [comment]
It's been added in v0.8 now. Feel free to report an issue if you have any problems with it.
