### ISSUE TITLE
[MGS3] Disabled Background Input doesn't seem to work

### ISSUE THREAD

**Issue by TheKrzysiek** [Lyall/MGSHDFix#36]
I have it, windowed and borderless all enabled, but whenever I focus on another window the game still reacts to the keyboard inputs.

**Comment by emoose** [comment]
Could you post your MGSHDFix.log file here? Maybe something isn't being applied properly.
Also how are you switching from the game window, ALT+TAB or something else?

**Comment by TheKrzysiek** [comment]
[MGSHDFix.log](https://github.com/Lyall/MGSHDFix/files/13229919/MGSHDFix.log)

**Comment by emoose** [comment]
>MG/MG2 | MGS 2 | MGS 3: Disable Background Input: Pattern scan failed.

Hm seems it couldn't find the code needed for it some reason, maybe you're playing with JP exe or a different game ver, could you upload your METAL GEAR SOLID3.exe file somewhere to check with? It might be too big for github but you could upload on a different site, like https://wetransfer.com (click 3 dots to change it to "get transfer link")

**Comment by TheKrzysiek** [comment]
[METAL GEAR SOLID3.zip](https://github.com/Lyall/MGSHDFix/files/13230101/METAL.GEAR.SOLID3.zip)

I'm playing the european version.
I edited it before the patches came out to play at 1440p, and I'm not sure if I changed it to default exe, so that may be the issue.
I'll try removing it and re-downloading the default one.

**Comment by TheKrzysiek** [comment]
I got the default exe and it still doesn't work

**Comment by fnaf135** [comment]
> I got the default exe and it still doesn't work

Did you try to just enable only either windowed or borderless then test it again?

**Comment by TheKrzysiek** [comment]
> Did you try to just enable only either windowed or borderless then test it again?

I just tried that, still didn't work.
I also tried the North American version and the same result.

**Comment by fnaf135** [comment]
Had you downloaded the latest fix frohttps://github.com/ThirteenAG/Ultimate-ASI-Loader/releases/download/x64-latest/d3d11-x64.zip and replace it to the one that came included in the fix archive

**Comment by emoose** [comment]
Strange, game EXE seems to match up with my one, not sure why pattern scan would fail.

If the updated asi loader above doesn't help, could you try with this ASI and post the log from it? Should tell us which of the patterns specifically is broken.

[MGSHDFix_0.8_bglog.zip](https://github.com/Lyall/MGSHDFix/files/13231698/MGSHDFix_0.8_bglog.zip)

**Comment by fnaf135** [comment]
> Had you downloaded the latest fix from "releases" tag? If it still happens, maybe you can try download the latest Asi Loader from here https://github.com/ThirteenAG/Ultimate-ASI-Loader/releases/download/x64-latest/d3d11-x64.zip and replace the dll that came included in the fix archive with the new Asi loader you just downloaded into the game's directory

I just checked myself and I see that the problem is not from the Asi Loader as the one included in the fix still works for me, maybe it was from either the ini or the asi file itself. Have you set the Disable Background Input to "true"? Maybe you can upload the "MGSHDFix.log" so I can check if the fix was enabled in the code or not

**Comment by TheKrzysiek** [comment]
> Strange, game EXE seems to match up with my one, not sure why pattern scan would fail.
> 
> If the updated asi loader above doesn't help, could you try with this MGSHDFix build and post the log from it? Should tell us which of the patterns specifically is broken.
> 
> [MGSHDFix_0.8_bglog.zip](https://github.com/Lyall/MGSHDFix/files/13231698/MGSHDFix_0.8_bglog.zip)

Just tried both this and the ASI loader, Disable Backround Input and everything else is set to true, still the same.

**Comment by emoose** [comment]
Could you post the MGSHDFix.log from that bglog build? Should tell us which patterns it failed to find.

**Comment by fnaf135** [comment]
> > Strange, game EXE seems to match up with my one, not sure why pattern scan would fail.
> > If the updated asi loader above doesn't help, could you try with this MGSHDFix build and post the log from it? Should tell us which of the patterns specifically is broken.
> > [MGSHDFix_0.8_bglog.zip](https://github.com/Lyall/MGSHDFix/files/13231698/MGSHDFix_0.8_bglog.zip)
> 
> Just tried both this and the ASI loader, Disable Backround Input and everything else is set to true, still the same.
Could you also post a screenshot of your game's folder so I can see how it looks like too?

**Comment by fnaf135** [comment]
> > Strange, game EXE seems to match up with my one, not sure why pattern scan would fail.
> > If the updated asi loader above doesn't help, could you try with this MGSHDFix build and post the log from it? Should tell us which of the patterns specifically is broken.
> > [MGSHDFix_0.8_bglog.zip](https://github.com/Lyall/MGSHDFix/files/13231698/MGSHDFix_0.8_bglog.zip)
> 
> Just tried both this and the ASI loader, Disable Backround Input and everything else is set to true, still the same.

Could you also post a screenshot of your game's folder so I can see how it looks like too?

**Comment by TheKrzysiek** [comment]
Oh, I just noticed I had the old ALTTAB patch still in the files.

Removed it and it works fine now.

That was very dumb of me.
