### ISSUE TITLE
Use DXVK and this mod

### ISSUE THREAD

**Issue by kavitormorsch** [Lyall/MGSHDFix#37]
I can't install this mod and DXVK(need this otherwise my game won't open), is there any way to use both dll's at the same time?

**Comment by NyaomiDEV** [comment]
There's no need to have DXVK on Windows (if it only opens with DXVK it means you should fix your drivers). On Linux, however, Proton already comes with DXVK; if you're not running the game via "official" means, then you should use Winetricks to install DXVK and then install this mod the way it's meant to be installed.

**Comment by kavitormorsch** [comment]
> There's no need to have DXVK on Windows (if it only opens with DXVK it means you should fix your drivers). On Linux, however, Proton already comes with DXVK; if you're not running the game via "official" means, then you should use Winetricks to install DXVK and then install this mod the way it's meant to be installed.

I don't know if it's a driver issue, various other people had the same issue and adding DXVK files in the game directory helped them.

**Comment by fnaf135** [comment]
Just rename the asi loader dll file to "winmm.dll"

**Comment by NyaomiDEV** [comment]
> I don't know if it's a driver issue, various other people had the same issue and adding DXVK files in the game directory helped them.

You should perform a full driver reinstall with the latest version you can for your graphics card. It is advised to use DDU (Display Driver Uninstaller) to fully clean up previous driver installations.

There is no way in hell you are forced to run DXVK on Windows.

**Comment by kavitormorsch** [comment]
> Just rename the asi loader dll file to "winmm.dll"

Worked, thanks.
