### ISSUE TITLE
Windowed/borderless modes

### ISSUE THREAD

**Issue by emoose** [Lyall/MGSHDFix#4]
Would be nice to add windowed & borderless options, for windowed mode I found a pretty easy patch for it (included in the steam forums mod), haven't seen any major issues from that yet, though it did need an extra patch to hide mouse cursor since game was calling `SetCursor` all the time.

(for finding that patch, it seems the Renderer.dll they shipped isn't actually a DLL but a .lib file with function names & a couple structs, from that I saw a `CRenderBackend::CreateSwapChain` func gets called by `CRenderBackend::CRenderBackend` with a param that sets it fullscreen, changing that param in the EXE from 1 to 0 seems to be enough to let it stay in windowed mode.)

Seems the game actually has some logic for storing/retrieving window position too, but not really sure how good that is, saw a few mentions that moving the window had issues.

Tried looking into making it borderless too, AFAIK this usually just needs the `CreateWindowExA` style parameter changed to remove the border/maximize/minimize/etc flags, but when I tried that with this the game window just failed to render, cursor would stay locked in the borders it should have but nothing showed, not sure what's up with that... game does seem to have weird code for rendering the window as a child window of something else, maybe that's interfering somehow.

**Comment by Lyall** [comment]
I've added a windowed mode toggle to the next version thanks to your work. I also had a look at the `CreateWindowExA` call and tried changing the style to be borderless but it just crashes for me.

So the window style it's using is `0x10CF0000` which presumably would be:
```
WS_VISIBLE
0x10000000
WS_THICKFRAME
0x00040000
WS_CAPTION
0x00C00000
WS_SYSMENU
0x00080000
WS_MAXIMIZEBOX
0x00010000
WS_MINIMIZEBOX 
0x00020000
```
I tried altering it to `0x80CF0000` which would be swapping `WS_VISIBLE` for `WS_POPUP`. But that causes an instant crash.

**Comment by Lyall** [comment]
Here is a test build with the latest commits and the borderless option. I assuming `0x90000000` (`WS_VISIBLE` + `WS_POPUP`) is correct for borderless, but I'm not that familiar with the Windows API.

[MGSHDFix_v_0_6_test.zip](https://github.com/Lyall/MGSHDFix/files/13184401/MGSHDFix_v_0_6_test.zip)

**Comment by emoose** [comment]
Ah nice that seems to work for me, did notice with borderless the game window still didn't render at first, but after a few seconds it loaded up fine, maybe just didn't wait long enough before 😅 

Maybe worth looking into whether we can get it to paint black immediately somehow, just so people won't think game has frozen, not sure if this could just be something on my end tho, do you also have to wait a little before the game starts?

**Comment by Sasha349** [comment]
While using borderless window with 2560x1440 resolution with 150% windows scaling Image out of bounds. Used 0.6 fix version

**Comment by emoose** [comment]
@Sasha349 could you drop your MGSHDFix.log in here? Just to let us know the settings used and if they applied properly.

Did you play the game in windowed mode at all (non-borderless)? If the window was moved in windowed mode it might have saved the placement for it.

Also could you try right clicking the MGS EXE (not launcher.exe) > properties > compatibility > high DPI settings > check Override scaling behavior, set the dropdown to Application, and see if it makes any difference?

**Comment by Sasha349** [comment]
![untitled](https://github.com/Lyall/MGSHDFix/assets/48595354/bb5e7199-0cae-4d70-bc92-8255345e8e6a)
[MGSHDFix.log](https://github.com/Lyall/MGSHDFix/files/13196786/MGSHDFix.log)

im confuse you. not out of border. seems like it overscaled. only in mgs2. ovverride scaling not helped. fullscreen work correct. seems  it run in full 4k, because screens are full

**Comment by Lyall** [comment]
@Sasha349 Does this same problem happen with borderless/windowed mode disabled? I suspect this is related to #19.

**Comment by Sasha349** [comment]
my specs: Windows resolution 2560x1440. Game resolution 2560x1440. Monitor resolution 3840x2160.
in fullscreen game run in 4k. seems game ignore ini setting and run in max monitor resolution

**Comment by Lyall** [comment]
I have reworked the framebuffer fix to make the game think your max supported resolution is the same as the desktop resolution. This should in theory fix the issue you are having. Can you please try this test build out and let me know how it goes?

[MGSHDFix_v_0_7_framebuffer.zip](https://github.com/Lyall/MGSHDFix/files/13222316/MGSHDFix_v_0_7_framebuffer.zip)

**Comment by Sasha349** [comment]
![20231101035420_1](https://github.com/Lyall/MGSHDFix/assets/48595354/4e7aea73-9603-4941-9a86-3991716c147f)
[MGSHDFix.log](https://github.com/Lyall/MGSHDFix/files/13222366/MGSHDFix.log)
still ignore settings(

**Comment by Lyall** [comment]
Hmm, that's odd. So it's running at 2560x1440 and scaling up to a 3840x2160 window? Does this happen without borderless mode on?

**Comment by Sasha349** [comment]
Yes. in fullscreen mode too

**Comment by ShizCalev** [comment]
Fixing broken issues, ignore this message.
