### ISSUE TITLE
Crashing in mgs2 in video codec calls

### ISSUE THREAD

**Issue by Basszajba** [Lyall/MGSHDFix#42]
The first time when the player encounters c4 the following video codec call with Otacon crashes the game 

additional information 
Hardware used: steam deck
Compatibility: proton experimental
Resolution:800p 16:10

**Comment by TacoDeBoss** [comment]
This is a known issue on Proton / Linux, including Steam Deck. Even the XAudio workaround does not currently fix this. You'll probably have to wait for Valve to finish patching up Proton to support the media codecs of MGS2/3.
