### ISSUE TITLE
Use without needing the game's launcher

### ISSUE THREAD

**Issue by Arikdefrasia** [Lyall/MGSHDFix#50]
I had assumed I was the only one that was having issues with this mod not working as I saw no body else saying the same.  I now realize that it's because I renamed METAL GEAR SOLID 3.exe to launcher.exe as to skip the launcher and have steam go directly into the game, which evidently negates nearly every feature of this mod and the game actually looks worse.  Is it possible to remedy this and still bypass the launcher?  

For what it's worth, the [MGSResolutionPatch](https://github.com/Sergeanur/MGSResolutionPatch) mod works fine in this scenario but lacks the other features of MGSHDFix

**Comment by fnaf135** [comment]
You can try rename your game's files' name back to their original names, then go to your Steam Library, right click on your MGS3 game choose "Properties", then under the "Launch Options", type in this: "(Your game's exe file directory)" %command%, then close the tab and you should be able to launch the other exe file via Steam

**Comment by fnaf135** [comment]
The fix wouldn't work because it checks and run via "METAL GEAR SOLID3.exe" specific file, not the launcher one

**Comment by Arikdefrasia** [comment]
> You can try rename your game's files' name back to their original names, then go to your Steam Library, right click on your MGS3 game choose "Properties", then under the "Launch Options", type in this: "(The exe file you want to run's directory)" %command%, then close the tab and you should be able to launch the other exe file via Steam

Perfect! Noticed some aliasing but fixed that through Nvidia control panel and now looks marvelous. Thank you!
