### ISSUE TITLE
Option to downscale?

### ISSUE THREAD

**Issue by GamerzHell9137** [Lyall/MGSHDFix#52]
Realized its not working. Settings the custom resolution to something greater than your monitor size and settings the screen to borderless makes the screen only fill for the resolution of the screen while everything else gets out of bound of the resolution eg. only 1/4 of the game is shown if you set the custom resolution to 4K but have a 1080p screen.

Any way to make it possible output 4k in a 1080p screen size?

**Comment by Lyall** [comment]
> The downsampling works in my PC while using exclusive fullscreen. Using borderless fullscreen makes the image appear cropped.

This is correct, you'll have to use fullscreen mode for downsampling with DSR/VSR or a higher than native resolution.
