### ISSUE TITLE
Is it possible that games have a blacklist (or, failing that, a whitelist) of supported graphics cards?

### ISSUE THREAD

**Issue by fabrebatalla18** [Lyall/MGSHDFix#55]
Is it possible that games have a blacklist (or, failing that, a whitelist) of supported graphics cards?

My doubt arises because with old cards the game does not even start, it is not that it is slow or has problems, it is that as soon as you start the main exe a white window simply opens for a few seconds and does absolutely nothing. I have noticed that this happens with games that have 64-bit libraries (steam_api64.dll)

**Comment by emoose** [comment]
Haven't seen any kind of lists so far, only thing I can think of is D3D11 feature support, that or did notice game has issue starting if you don't have an audio device enabled, some graphics cards do include an audio device too but not all, maybe the ones you had issues with didn't enable any devices?
