### ISSUE TITLE
Crashing back to desktop on steam version 1.3.0

### ISSUE THREAD

**Issue by ProtonicCobra** [Lyall/MGSHDFix#64]
The recent update to MGS2 and 3 crashes with using this, shows its playing and maybe even shows the loading screen and then just force quits. I'm presuming it's due to the launcher edits they've made to the launchers.

I'm sure you're aware of the recent update to the collection and you're already working on an update but I thought i'd just post a thing of it. feel free to close it if not needed #

**Comment by ShizCalev** [comment]
No crashing here with the latest update and MGSHDFix v1.0 (both skipping launcher and going through the launcher.) 

May want to verify your game's files through steam, and post your logfile.

**Comment by ProtonicCobra** [comment]
sure ill give that a go.
incase it doesnt work where are the log files stored?

**Comment by Lyall** [comment]
I've also quickly tested out MGS3 yesterday, and MGS2 with today's patch and they seem to still work fine. 

> sure ill give that a go. incase it doesnt work where are the log files stored?

The log should be `MGSHDFix.log` and it will be in the game folder next to the main executable.

**Comment by ProtonicCobra** [comment]
thanks for the replies, im gonna try this now. im thinking the update has overwritten the ASI loader so ill try it again and if dont have any luck ill post logs :)

**Comment by ProtonicCobra** [comment]
Thanks all for your help sorry for wasting your time with this. huge error on my part
