### ISSUE TITLE
HD Fix not working anymore

### ISSUE THREAD

**Issue by DocPhantom123** [Lyall/MGSHDFix#68]
Hey, i was really enjoying the MGSHDFix on Nov 19th when i discovered the crouch walking mod on Nexus Mods.
Sadly after working a week and not being able to play i found out that the MGSHDFix is not working anymore for some reason.
It is not skipping the intros and not applying any resolution i give it.

Is this already known?

Im currently trying to revert to a Steam version from Nov 14th to try and see if this version fixes the problems i am currently facing, though Steam Depot downloading is pretty slow and after 6 hours i have downloaded 4,3GB/9,7GB...

I would love to see a fix for this.
I can also supply the .log file which is created after starting the game.

**Comment by Lyall** [comment]
As far as I can tell it still works fine on the latest version on Steam (1.3.0). Can you post the log file?

**Comment by DocPhantom123** [comment]
Sure!
It never skips the "Konami Presents" Snake Eater Intro for me and i can not use my Xbox Controller.. 
Tried several reinstalls, older versions none fixed the problem im facing.
You can find my .ini below and .log attached.
I ONLY installed HDFix for now since all the other mods worked for some reason...
[MGSHDFix.log](https://github.com/Lyall/MGSHDFix/files/13467441/MGSHDFix.log)

.ini: (Only the settings i changed)
Width = 3840
Height = 2160
Borderless = true

SkipLauncher = true

CtrlType = XBOX
Language = EN
Region = EU


I have also not updated any drivers on my system.
Im using the following hardware:

Ryzen 7 5800x3D
64GB DDR4
RTX 4080

**Comment by Lyall** [comment]
Hmm that's odd. Your log looks good, as if everything is working fine. 

So to confirm, you're getting the typical logos still like Konami and Bluepoint? You also mentioned your controller not working, does that mean it's actually not registering input or is it that the icon override isn't working?

**Comment by DocPhantom123** [comment]
When the Fix and all the other mods worked i booted up the game and was instantly into the MGS3 screen where i can press Start or Tab to get to the "Load Save" screen.

After leaving my PC off for the whole week and trying to play again (I did not see any updates for the game) it somehow "broke".
I now see the "Konami Presents" Snake Eater Song intro when i have "SkipLauncher = true" enabled, and when its disabled i see the red "Konami" Splash screen with Bluepoint ect..

The game seems to not register any input after i hit "Tab" to skip the Snake Eater intro song.
I see all the Icons, even tried to switch it to PS5 which also did not register any input, but changed the icons.

If you want i could probably make a private YouTube Video showing that i downloaded the game freshly and installed MGSHDFix with the .ini i changed for myself and that i get this problem.

**Comment by DocPhantom123** [comment]
I have created a Video showcasing my problem.
https://youtu.be/1GJeeebZExk

You can find the .log for this showcase attached.
[MGSHDFix.log](https://github.com/Lyall/MGSHDFix/files/13467577/MGSHDFix.log)

I hope that we can find an error since i love the game and the mod is awesome!

**Comment by Lyall** [comment]
Sorry for the late reply, I was waiting for the YouTube video to finish processing so I could read the text, then forgot about it!

I'm really not sure why it's not working for you. Watching the video you posted, it show it's all installed to the correct location, you've got a fresh install and it's generating complete log files which implies it is working fine. 

My only guess could be that something is happening on game start-up that's causing issues. I saw it popup with AutoHDR in your video. I wouldn't think that would cause issues but are you able to try launching it with AutoHDR off? Apart from that I'm honestly really not sure what's causing your issue. I wish I had a better answer to give you.

**Comment by DocPhantom123** [comment]
Hey, thanks for the quick response!
No worries.

ill try it without HDR after work, might be the problem since i have not used HDR before where it worked, but i guess we will see..

Otherwise ill try a new Windows 11 installation and maybe fix it that way.

**Comment by kimeikato** [comment]
Judging by the video, everything seems to be working. The actual intro videos of MGS2 and 3 are not skipped. Only the launcher and logos. Correct me if I'm wrong😅. 

MGS3 skips the intro the first time through until you start Operation snake eater (or select "I like MGS3" on startup). 

I suspect the above behavior is causing confusion 🙂 .

**Comment by DocPhantom123** [comment]
Are you sure?
Once i installed it the first time i never got the „Snake Eater“ Video playing since i was brought right into the CQC Animation Screen where i can Press a button to continue.
i will try it after work, will get back with some feedback.

**Comment by DocPhantom123** [comment]
OMG i am soooooo embarrassed....
It worked all the time but my Controller was connected to ym iPad hence why i was not able to use it.
Im so bloddy sorry for any inconviniences.... Sorry...
kimeikato was totally right!

**Comment by Lyall** [comment]
No worries, glad to hear it's working for you now!
