### ISSUE TITLE
[MGS3] Windowed Borderless does not work.

### ISSUE THREAD

**Issue by ProbablyWorth** [Lyall/MGSHDFix#73]
I tried the following settings:

Windowed = false
Borderless = true

and

Windowed = true
Borderless = true

And It is still fullscreen.

**Comment by IkariBrendo** [comment]
Bruh

**Comment by ShizCalev** [comment]
Both need to be set to true.

**Comment by ProbablyWorth** [comment]
> Bruh
> 
> 
> 
> You want it windowed and you want it borderless. Come on now.
sorry i was kinda in a rush typing this

**Comment by ProbablyWorth** [comment]
> Both need to be set to true. 


sorry i was in rush typing, yes i have set it to true.

**Comment by ShizCalev** [comment]
Can you send your .log file please?

**Comment by ProbablyWorth** [comment]
> Can you send your MGSHDFix.log file please? 

yes when i get home, not home rn

**Comment by ProbablyWorth** [comment]
> Can you send your MGSHDFix.log file please?

[MGSHDFix.log](https://github.com/Lyall/MGSHDFix/files/13575533/MGSHDFix.log)

**Comment by Manguydood** [comment]
I've run into the same issue. Windowed Borderless seems to work on the _launcher_ but not on the actual game. 
Everything else seems to be functioning.

**Comment by Colton-White** [comment]
IT DOESN'T WORK FOR ME TOO :(

**Comment by soundsofsilence** [comment]
[MGSHDFix.log](https://github.com/Lyall/MGSHDFix/files/14017170/MGSHDFix.log)
Having the same issue.

**Comment by SpriggsyUK** [comment]
[MGSHDFix.log](https://github.com/Lyall/MGSHDFix/files/14025546/MGSHDFix.log)
Same issue for me too
