### ISSUE TITLE
[feature request] fix texture scaling for plant intro title texture 

### ISSUE THREAD

**Issue by ShizCalev** [Lyall/MGSHDFix#74]
how it should look:
![2131640_20231209162437_1](https://github.com/Lyall/MGSHDFix/assets/6209658/6e0e970a-9c1b-4ff4-8ddb-119800d8b2e8)

how it looks when increased 
![2131640_20231209222335_1](https://github.com/Lyall/MGSHDFix/assets/6209658/1b880278-b25e-426c-9f09-dfc518333dd5)

plant intro title screen texture doesn't scale properly when texture size is increased.

**Comment by ShizCalev** [comment]
example files:
[textures.zip](https://github.com/Lyall/MGSHDFix/files/13626682/textures.zip)

i believe the loading screen icons have the same issue too, Misc/Loading/_win/loading.ctxr & loading_jp.ctxr

**Comment by Noname00000001** [comment]
Weird issue, I don't recall having this issue myself. 
Although it might not fix your issue, I'll suggest trying out this mod.
https://www.nexusmods.com/metalgearsolid2mc/mods/21/
A brilliant mod by Afevis on NexusMods that restore the title cards both in-game and in the menus closer to their original state from the PS2.

**Comment by ShizCalev** [comment]
> Weird issue, I don't recall having this issue myself. Although it might not fix your issue, I'll suggest trying out this mod. https://www.nexusmods.com/metalgearsolid2mc/mods/21/ A brilliant mod by Afevis on NexusMods that restore the title cards both in-game and in the menus closer to their original state from the PS2.

I AM Afevis. I identified the issue while making that mod. :p
