### ISSUE TITLE
[Feature Request] Mouse Cursor toggle in the Launcher possible?

### ISSUE THREAD

**Issue by Noname00000001** [Lyall/MGSHDFix#76]
Hello!

I'm well aware of the mouse cursor toggle for the games, but I was wondering if it could be expanded to work in the launchers (MGS2 and 3) itself somehow?

**Comment by Lyall** [comment]
This should be added in the next release.

**Comment by Noname00000001** [comment]
Cheers and thanks for the incredible work you and everybody contributing have done!
