### ISSUE TITLE
Latest 1.4.0 Patch has broken the pillarboxing fix

### ISSUE THREAD

**Issue by Menergy1984** [Lyall/MGSHDFix#77]
With the release of Patch 1.4.0 MGS2/3 black bars return on both sides of my screen despite the "[Fix Aspect Ratio]" set to enabled.

The only solution for me is to use CRU (Custom Resolution Utility) to delete the odd resolutions added by my TV however I loved the convenience of the MGSHDFix automatically fixing the issue due to the fact that every time I install a new driver I have to use CRU again to delete those odd resolutions.

I'm sure myself and many others who use a TV as a monitor would greatly appreciate a fix for this issue, thank you so much for phenomenal and most essential mod. 

I have created and maintained a Mod list and guide on Steam for a few weeks now on steam https://steamcommunity.com/app/2131650/discussions/0/3943524562532474432/ with credits to all authors for their amazing work fixing this mess.

**Comment by gnrdeth13** [comment]
Came here to report the same. The black bars are on the left-right sides of the screen for me as well, no matter what settings I choose in the MGSHDFix.ini file. Btw, thanks [Menergy1984](https://github.com/Menergy1984) for the awesome mod guide! I used it to enhance the game. I just hope the newest patch didn't break anything else from the list you provided. I didn't want to use the CRU method to resolve the black bars, but looks like that's the only way at present.

Totally off topic, but I haven't been able to use sonar either. I can equip it, but no button on my DS4 will activate it.
![mgs3-black-bars-despite-MGSHDFix](https://github.com/Lyall/MGSHDFix/assets/124783515/9da4cc2d-b09e-4956-afbc-d204908bb3b2)

**Comment by mooms06** [comment]
> Totally off topic, but I haven't been able to use sonar either. I can equip it, but no button on my DS4 will activate it.

I also have this issue. Do you hate teste without MGSHDFix ?

**Comment by gnrdeth13** [comment]
> > Totally off topic, but I haven't been able to use sonar either. I can equip it, but no button on my DS4 will activate it.
> 
> I also have this issue. Do you hate tested without MGSHDFix ?

I got sonar to work by long pressing L3. They changed it up from the old config. Used to be tapping L3 would activate it.

**Comment by Lyall** [comment]
Should be fixed as of v2.0.
