### ISSUE TITLE
The new volume menu added in update 1.4.0 is displayed at a lower resolution when using a custom resolution in MGS2 and MGS3.

### ISSUE THREAD

**Issue by Solopoio** [Lyall/MGSHDFix#78]
I'm playing at 1920x1080 custom resolution, I would say the menu is showing at 720p.

MGS2: To access this sound menu ingame you must first pause it ( press "start" ) and then press R1+L1 or RB+LB.
(There is no other way)

![image](https://github.com/Lyall/MGSHDFix/assets/154438031/697e07cf-c46d-4d42-bfde-8267543a1b51)
![image](https://github.com/Lyall/MGSHDFix/assets/154438031/b7ab4cc7-421d-403a-9de3-2c61268b91bc)
![image](https://github.com/Lyall/MGSHDFix/assets/154438031/61939c31-3a20-4c1d-9993-6d7a5d968223)

MGS3: This sound section can be found ingame on the survival viewer or in the main menu.

![image](https://github.com/Lyall/MGSHDFix/assets/154438031/a0e5e01f-45a2-4fe7-8f0f-508a4866b620)
![image](https://github.com/Lyall/MGSHDFix/assets/154438031/12354040-c31f-47f6-ac61-8f0796021279)
![image](https://github.com/Lyall/MGSHDFix/assets/154438031/3cc3e818-3e34-4c90-847c-a9ddd4a24254)
![image](https://github.com/Lyall/MGSHDFix/assets/154438031/4f80b5bf-f04c-4d39-853a-3c0bdd520b0a)

PD: Regardless of the resolution, the menu and sound options work fine

**Comment by Lyall** [comment]
This will be fixed in the next release.

![ezgif-2-516362274d](https://github.com/Lyall/MGSHDFix/assets/695941/75ed0a78-ae50-4b30-a650-76783396cc28)
