### ISSUE TITLE
The custom resolution does not work properly after update 1.4.0 on MGS2 and MGS3.

### ISSUE THREAD

**Issue by Solopoio** [Lyall/MGSHDFix#79]
The options "Windowed" and "Borderless" doesn't work as intended, the game always launch on fullscreen. 

![image](https://github.com/Lyall/MGSHDFix/assets/154438031/4d4d25f4-ef3f-4607-8e35-390bc0449eb2)

After this new update, if you launch the game on fullscreen (via the launcher, setting the option on fullscreen) you can still get windowed and windowed borderless even without the mod.

Fullscreen -> (1st ALT+ENTER) -> Windowed -> (2nd ALT+ENTER) -> Windowed Borderless.

Pd: 

After doing this, you will not be able to return to fullscreen.

You can also launch the game on windowed (via the launcher, setting the option on windowed) and just one ALT+ENTER will be needed to get the windowed borderless.

**Comment by Lyall** [comment]
Should be fixed as of v2.0.
