### ISSUE TITLE
Apparently doesn't work anymore. Tested on MG1/2, MGS2 and they all crash, since 1.4.0 patch. I think a new release of the mod is needed.

### ISSUE THREAD

**Issue by LorenzoKy** [Lyall/MGSHDFix#81]

**Comment by LethalPlacebo** [comment]
Everything in the mod is working just fine for me across all supported games with patch 1.4.0, with the exception of the windowed modes. I'd suggest you try reinstalling the mod and see if anything changes.

**Comment by LorenzoKy** [comment]
> Everything in the mod is working just fine for me across all supported games with patch 1.4.0, with the exception of the windowed modes. I'd suggest you try reinstalling the mod and see if anything changes.

Okay, i'll try, with windowed you mean borderless too?

**Comment by LethalPlacebo** [comment]
> > Everything in the mod is working just fine for me across all supported games with patch 1.4.0, with the exception of the windowed modes. I'd suggest you try reinstalling the mod and see if anything changes.
> 
> Okay, i'll try, with windowed you mean borderless too?

Yeah, neither one works, so set both "Windowed" and "Borderless" to "false" and the rest of the mod should work just fine.

**Comment by asp0909** [comment]
I confirm! It does not work for me either! update 1.4.0

**Comment by LethalPlacebo** [comment]
> I confirm! It does not work for me either! update 1.4.0

Again, most of the mod should work just fine with the exception of the "Windowed" and "Borderless" options, have you tried reinstalling the mod?

**Comment by MasterDarkseid** [comment]
Yeah the patch is broken. Needs some update for the new patch. I feel like the patch should remove windowed mode as it's in game now. Borderless tho should be kept.

**Comment by Noname00000001** [comment]
Where are people exactly crashing? I have no problem launching either MGS2 or 3 into the in game menus, with the resolution matching my screen (0 in both x and y9. I'm not using the Skip Launcher or the Window/Borderless options.

What other setting are you using, skipping launcher etc.

Have you tried reinstalling the mod, like mentioned.  

A "it is broken" without telling what settings you might be using and if you tried reinstalling the mod honestly ain't worth much. They need info to be able to fix things.

**Comment by MasterDarkseid** [comment]
For me it doesn't crash However those happen.
1. V-sync is off (cause tearing with the patch)
2. The 1440p isn't truly 1440p anymore (might be due to windowed and borderless not working anymore)

The rest seems to work just fine (i think)

**Comment by LethalPlacebo** [comment]
> For me it doesn't crash However those happen.
> 
>     1. V-sync is off (cause tearing with the patch)
> 
>     2. The 1440p isn't truly 1440p anymore (might be due to windowed and borderless not working anymore)
> 
> 
> The rest seems to work just fine (i think)

V-sync works fine for me in Fullscreen mode with the mod installed, resolution is also set correctly for me at 1440p. Have you tried disabling the mod's windowed modes and playing in Fullscreen?

**Comment by MasterDarkseid** [comment]
Yeah, i did. It seems it's only with MGS3. MGS2 and MG1/2 are working just fine.

**Comment by mooms06** [comment]
MGSHDFix 1.0.1 with default options is also crashing with MGS3 1.4.0 here. 
MGSHDFix 0.9 is working.

**Comment by emoose** [comment]
@mooms06 could you drop 1.0.0/1.0.1 log file here if it's being created?

**Comment by mooms06** [comment]
> @mooms06 could you drop the 1.0.0/1.0.1 log file here if it's being created?

Sure, here is 1.0.1 log:
[MGSHDFix.zip](https://github.com/Lyall/MGSHDFix/files/13806301/MGSHDFix.zip)

**Comment by mooms06** [comment]
Tried MGS 2, it also crashes with 1.0.1 but works with 0.9.

**Comment by AkiraJkr** [comment]
[MGSHDFix.log](https://github.com/Lyall/MGSHDFix/files/13868449/MGSHDFix.log)
I'll just drop my log but basically same thing as others, pattern scans fail, mod doesn't work properly the way it normally should. I can't even use alternative injection methods because of this(like Special K's ASI loader) like I used to before the game's latest update.

**Comment by Colton-White** [comment]
_**It doesn't work for me too! but without any crash :)**_ 
I installed the mod correctly, so that's why I'm sure it doesn't work!! specially things like custom res or windowed & borderless :/ ( skip launcher works but it resets input format to controller !!! ) 
... anyway ... I uninstalled it to install DXVK bc I want to play it on my GPU not CPU ( I have slow mo snake problem & I'm trying to find a way to fix it )
**for custom res this mod worked for me as well**  👇
( https://steamcommunity.com/app/2131650/discussions/0/3879347492856210943/ )
**to play windowed & borderless** Alt + Enter in launcher make the game to run in windowed mode

**Comment by Lyall** [comment]
Should be fixed in v2.0.

**Comment by CharmCitysKing** [comment]
this does not work 1000% if it does, i dont notice anythign other than i now can now press the windows key without the game minimizing. Graphics look 1:1 the same, UI, skyboxes....they must have just took everything you did and patched it in officially. i dont think this is really needed anymore TBH

**Comment by CharmCitysKing** [comment]
i dont think this works like it used to ever since 2.0 you can change the internal upscaling to WQHD which makes a HELL of a differnce compared to the FHD. (if you are on 2660x1440) but it does help with alot of QoL stuff. it does look a Liiiiiiiiiitle bit cleaner? I wish someone on youtube did a side by side comparison with this on and off. cause their are none :(

**Comment by ShizCalev** [comment]
> i dont think this works like it used to ever since 2.0 you can change the internal upscaling to WQHD which makes a HELL of a differnce compared to the FHD. (if you are on 2660x1440) but it does help with alot of QoL stuff. it does look a Liiiiiiiiiitle bit cleaner? I wish someone on youtube did a side by side comparison with this on and off. cause their are none :(

For FHD - the graphics should be 1:1. The launcher's FHD option natively increases the resolution to 1920x1080p, something which wasn't present in the game at all until just under a year ago.

All resolutions AFTER 1080p however are achieved through FSR upscaling when using the launcher's options (and the native resolution stays at 1080p) - and that's where you'll see the jump in quality between the mod vs the launcher.

At resolutions above 1080p, the FSR upscaling the launcher's options utilizes introduces tons of artifacting around the edges of everything - and also completely breaks mipmaps, making all textures extremely oversharpened / pixelated. These issues do not occur when using MGSHDFix



At 1080p, you just get all the other benefits of the mod - ie fixing effects that run at double speed, borderless windowed mode, fixing the size of lasers/rain/HUD elements that don't scale up properly with resolution (you can quickly compare all this stuff in-game by hitting Insert & Delete on your keyboard), fixing broken achievements, and all the other features that are listed in our readme file. :)
