### ISSUE TITLE
MGS 2 & 3 slowdown after increasing resolution!

### ISSUE THREAD

**Issue by madgust02** [Lyall/MGSHDFix#83]
The game runs really slow after increasing the resolution. I have only tested the intro part. The codecs seem to run smoothly but the cutscenes and gameplay are both very choppy. Is there a setting I need to know about? Or has the new patch for the game fu**ed up the mod? 

I have an RTX 3070 TI and a i7-10700k, so I should be fine.

EDIT: I have since tested MGS 3, and it runs slowly there as well. PLEASE HELP!

**Comment by LethalPlacebo** [comment]
With the exception of the windowed options, everything in the mod still works fine as of patch 1.4.0.

Did you manually increase the screen resolution in the mod's ini file? Or did you just leave both values at "0" to match your monitor's resolution?

**Comment by madgust02** [comment]
> With the exception of the windowed options, everything in the mod still works fine as of patch 1.4.0.
> 
> Did you manually increase the screen resolution in the mod's ini file? Or did you just leave both values at "0" to match your monitor's resolution?

I tried both, and I get slowdown no matter what.

**Comment by LethalPlacebo** [comment]
And you have confirmed that the slowdown only occurs when you have the mod installed, right? You've tested the game without the mod and the slowdown is gone?

Also I know you posted your specs but are you on a desktop or laptop?

**Comment by madgust02** [comment]
> And you have confirmed that the slowdown only occurs when you have the mod installed, right? You've tested the game without the mod and the slowdown is gone?
> 
> Also I know you posted your specs but are you on a desktop or laptop?

I am on a desktop, and the games run great without the mod. I played all of MGS 2 without the mod, and there where no problems. Currently playing MGS 3 now, and there have been no issues so far.

**Comment by LethalPlacebo** [comment]
That's really strange. I'd recommend uploading your MGSHDFix.log here and wait for one of the devs to take a look at it. Sorry I couldn't be of more help.

**Comment by madgust02** [comment]
> That's really strange. I'd recommend uploading your MGSHDFix.log here and wait for one of the devs to take a look at it. Sorry I couldn't be of more help.

Alltough, I have noticed some of the cutscenes get a little slow during a lot of action on screen. Maybe there is something I need to adjust?

**Comment by LethalPlacebo** [comment]
> > That's really strange. I'd recommend uploading your MGSHDFix.log here and wait for one of the devs to take a look at it. Sorry I couldn't be of more help.
> 
> Alltough, I have noticed some of the cutscenes get a little slow during a lot of action on screen. Maybe there is something I need to adjust?

I assume this is without the mod installed, which is very strange. It sounds as if it's not using the GPU or something. Longshot here, but you could try setting the game to prefer maximum performance on your GPU using the Windows "Graphics" settings screen.

**Comment by madgust02** [comment]
> > > That's really strange. I'd recommend uploading your MGSHDFix.log here and wait for one of the devs to take a look at it. Sorry I couldn't be of more help.
> > 
> > 
> > Alltough, I have noticed some of the cutscenes get a little slow during a lot of action on screen. Maybe there is something I need to adjust?
> 
> I assume this is without the mod installed, which is very strange. It sounds as if it's not using the GPU or something. Longshot here, but you could try setting the game to prefer maximum performance on your GPU using the Windows "Graphics" settings screen.

THAT WAS IT!!! God im dumb XD. Thank you so much!!

**Comment by LethalPlacebo** [comment]
> THAT WAS IT!!! God im dumb XD. Thank you so much!!
Not dumb at all, most games don't need this to be enabled unless you're on a laptop. Glad it's fixed, have fun! Also could you please mark this issue as "closed," it should be the purple button at the bottom.
