### ISSUE TITLE
Screen tearing + intro cutscene not displayed correctly (MGS3)

### ISSUE THREAD

**Issue by MasterDarkseid** [Lyall/MGSHDFix#89]
So, i don't know why but i have screen tearing i don't know if it's cause by the patch or update 1.4.0 but i didn't have the issue before 1.4.0.

However i have this issue.

![image](https://github.com/Lyall/MGSHDFix/assets/104478182/0d91dd46-a302-4021-954a-07e27a0ab3ca)

**Comment by LorenzoKy** [comment]
can you describe it better?

**Comment by MasterDarkseid** [comment]
Okay i think i'm wrong for the screenshot. I thought the screen background for intro to be completely black. However if you look more clearly there's some brighter background around the text. I guess it's normal behaviour.

However with more research i suppose my issues is not related to MGSHDfix. It's FPS unlocker the culprit. So i'm gonna close this issue.
