### ISSUE TITLE
[Bug] All Games: 100% Reproducable Frozen Process When Pressing Start on Controller While Game Minimized

### ISSUE THREAD

**Issue by ShizCalev** [Lyall/MGSHDFix#92]
Repo:
Have Xbox controller
Minimize Game
Press Start button (you can hear the game unpause when you do this.)
Restore game window
Game process is 100% frozen. Can't exit with Alt-F4 and can only be closed via task manager.

**Comment by Lyall** [comment]
I think I've been able to reproduce this on my end. It only seems to happen in non-borderless fullscreen mode. Is this the same for you?

**Comment by Lyall** [comment]
Can you try this test build? I narrowed the issue down to the SetWindowPos hook, so I've changed the way it's hooked and that seems to have sorted it on my end.

[MGSHDFix_v_2.1_test.zip](https://github.com/Lyall/MGSHDFix/files/14071850/MGSHDFix_v_2.1_test.zip)

**Comment by ShizCalev** [comment]
> Can you try this test build? I narrowed the issue down to the SetWindowPos hook, so I've changed the way it's hooked and that seems to have sorted it on my end.
> 
> [MGSHDFix_v_2.1_test.zip](https://github.com/Lyall/MGSHDFix/files/14071850/MGSHDFix_v_2.1_test.zip)

Working good here, no longer hanging!

**Comment by Lyall** [comment]
Should be fixed in v2.2
