### ISSUE TITLE
[Bug] [MGS2]: Fullscreen/borderless and other options arent working

### ISSUE THREAD

**Issue by spectkiller** [Lyall/MGSHDFix#99]
## Issue Summary:

As the title says, this thing isn't working for me. The mod is recognising the game alright but it is throwing errors later as per the log.

## MGSHDFix & Game Version Numbers: not sure about mgshd version but the mod version is 2.3

I am playing metal gear solid 2

## Log Files:
[MGSHDFix.log](https://github.com/Lyall/MGSHDFix/files/14613886/MGSHDFix.log)
![image](https://github.com/Lyall/MGSHDFix/assets/37000900/930c5016-af4b-44d6-b96d-55c4e8eb106d)

**Comment by LethalPlacebo** [comment]
I'm assuming the presence of "steamclient_loader.exe" and "ColdClientLoader.ini" means that this is a cracked/pirated copy. I don't think the mod authors support pirated versions of the game.

The only other thing I'll say is this: cracked copies of games usually contain edited exe files, which means that hex addresses that mods like MGSHDFix rely on to even work could be completely different.
